# Generated by Django 2.1.5 on 2019-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50)),
                ('f1', models.CharField(max_length=50)),
                ('f2', models.CharField(max_length=50)),
                ('f3', models.CharField(max_length=50)),
                ('f4', models.CharField(max_length=50)),
                ('f5', models.CharField(max_length=50)),
                ('f6', models.CharField(max_length=50)),
                ('f7', models.CharField(max_length=50)),
                ('f8', models.CharField(max_length=50)),
                ('f9', models.CharField(max_length=50)),
                ('f10', models.CharField(max_length=50)),
                ('creater', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('amount1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='groupmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('groupdetails', models.CharField(max_length=1000)),
            ],
        ),
    ]
