# Generated by Django 2.1.5 on 2019-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendexpense',
            name='exp_fri_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
