# Generated by Django 2.1.5 on 2019-03-16 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('exp_type', models.CharField(max_length=50)),
                ('exp_details', models.CharField(max_length=250)),
                ('exp_date', models.DateField(auto_now_add=True)),
                ('exp_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('exp_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user_exp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
